### ISSUE TITLE
Rename "Proposed Open Standard"

### ISSUE THREAD

**Issue by safrazier17** [interoperable-mobility/principles#7]
# Overview
The name "Proposed Open Standard" has caused confusion among the MDIP audience and is a source of concern particularly for prospective vendor signatories. We should change the name to better reflect the specific _kinds_ of proposals that meet the threshold for requiring support.

# Detail
The Principles define two types of standard, the open standard and the proposed open standard. Both types of standard must be supported by vendors and others seeking to achieve alignment with MDIP. The definition of Proposed Open Standard is:
> *Proposed Open Standard*
> Any specific ontology, schema, or format that: 
> Meets all the criteria of an [open standard](https://docs.google.com/document/d/1fdnx8p5VyW9A-entQZ8vo-WW9pCEZRNAXpmytjPpyJM/edit#heading=h.nzbxuglt75z0), 
> Has been transitioned to maintenance by an independent organization,
> Has at least one stable release as determined by the maintaining independent organization, and
> Has not met the standards for adoption as determined by the maintaining independent organization.

This definition was intended by coauthors to exclude many types of proposals. At the basic level we did not want to include standards which had been recently proposed but had little support, momentum or substance.

There are two opposing goals for the definition of Proposed Open Standard --> we want to 1) leverage MDIP to encourage vendors to become early (or earlier) adopters of standards that have demonstrated they are on a path to adoption and 2) not exact unduly onerous requirements on the vendor community such that they are uncomfrotable with aligning with MDIP.

Apart from any changes which might be made to the content of the definition of Proposed Open Standard, we should change the name of the term so as to better reflect those two goals. This will alleviate some audience concerns and also provide insight into what we are hoping to achieve through the inclusion of Proposed Open Standards.

**Comment by paulswartz** [comment]
The more I think about this, the more I think "Proposed Open Standard" is a fine name, and the it's the description which needs to change to better incorporate what the expectations are. 

I think the core features of a Proposed Open Standard are:
- free from cost and restrictions to use
- publicly documented
- at least one stable release
- open community of contributors / users with transparent governance
- implemented by at least one producer and one consumer excluding the original developer

These would seem to eliminate proposals which haven't been adopted by anyone, or proposals which aren't openly and freely available. To become a fully open standard, the ownership/governance/maintenance would also need to migrate.
