### ISSUE TITLE
Add new Coauthors and Cosignatories to site

### ISSUE THREAD

**Issue by safrazier17** [interoperable-mobility/principles#8]
# Requirements
* Add new coauthors `Los Angeles County Metropolitan Transportation Authority`, `North Carolina Department of Transportation`, and `Vermont Agency of Transportation` to:
** README.md
** Co-author section (add logos)
** Co-signatory section
* Add new cosignatories to Co-signatory section (in alphabetical order)
** [Snapper](https://www.snapper.co.nz/)
** [Vix](https://vixtechnology.com/)
** [City of Santa Monica Department of Transportation](santamonica.gov)
** [DCR Design](dcrdesign.net)
** [Open Mobility Data in the Nordics](https://nordicopenmobilitydata.eu/)
** Dr. Tierra Bills, University of California, Los Angeles
** [Fairsfair.org](fairsfair.org)
** Swiftly
** Foursquare ITP
** EnrouteQ

**Comment by safrazier17** [comment]
@thekaveman

**Comment by safrazier17** [comment]
@e-lo

**Comment by thekaveman** [comment]
Sorry @safrazier17, I will work on this today!

**Comment by safrazier17** [comment]
We have logo files I can send them to you tomorrow

**Comment by safrazier17** [comment]
looks good @thekaveman
